Repository eternnoir/pyTelegramBotAPI, pull requests merged in 2022-09, with the labels that each got.

#1703 Fix #1702
  telebot/asyncio_helper.py
Labels: bug, confirmed, under testing

#1710 Fixed difference between request_timeout and timeout.
  telebot/asyncio_helper.py
Labels: bug, help wanted, confirmed, code

#1707 raise other exceptions in antiflood function
  telebot/util.py
Labels: question, not confirmed

#1723 don't block loop
  telebot/async_telebot.py
Labels: bug

#1735 ⚙️ Added some frequent parameters to classes(see full list)
  telebot/__init__.py
  telebot/async_telebot.py
Labels: enhancement, comming soon, confirmed, bot api, code

#1736 Added a new bot to the list
  README.md
Labels: documentation

#1722 Handlers and Middlewares processing union
  telebot/__init__.py
  telebot/async_telebot.py
  telebot/ext/sync/webhooks.py
  telebot/storage/base_storage.py
  telebot/storage/memory_storage.py
  telebot/storage/pickle_storage.py
  telebot/storage/redis_storage.py
Labels: comming soon, confirmed, code
