Repository eternnoir/pyTelegramBotAPI, pull requests merged in 2022-11, with the labels that each got.

#1761 Extended exception handler behaviour for async
  telebot/async_telebot.py
Labels: bug, confirmed, code

#1783 Bot API 6.3 Update
  README.md
  telebot/__init__.py
  telebot/apihelper.py
  telebot/async_telebot.py
  telebot/asyncio_helper.py
  telebot/types.py
Labels: bot api, in the backlog, feature

#1801 Fixed bot api bug
  telebot/types.py
Labels: bug

#1808 Fix #1804
  telebot/types.py
Labels: bug, confirmed

#1811 Continuehandling fix
  telebot/__init__.py
  telebot/async_telebot.py
Labels: bug, confirmed

#1813 Русская документация(0%)
  docs/source/conf.py
  docs/source/locales/en/LC_MESSAGES/async_version.po
  docs/source/locales/en/LC_MESSAGES/calldata.po
  docs/source/locales/en/LC_MESSAGES/formatting.po
  docs/source/locales/en/LC_MESSAGES/index.po
  docs/source/locales/en/LC_MESSAGES/install.po
  docs/source/locales/en/LC_MESSAGES/quick_start.po
  docs/source/locales/en/LC_MESSAGES/sync_version.po
  docs/source/locales/en/LC_MESSAGES/types.po
  docs/source/locales/en/LC_MESSAGES/util.po
  docs/source/locales/ru/LC_MESSAGES/async_version.po
  docs/source/locales/ru/LC_MESSAGES/calldata.po
  docs/source/locales/ru/LC_MESSAGES/formatting.po
  docs/source/locales/ru/LC_MESSAGES/index.po
  docs/source/locales/ru/LC_MESSAGES/install.po
  docs/source/locales/ru/LC_MESSAGES/quick_start.po
  docs/source/locales/ru/LC_MESSAGES/sync_version.po
  docs/source/locales/ru/LC_MESSAGES/types.po
  docs/source/locales/ru/LC_MESSAGES/util.po
Labels: documentation

#1814 Translated into russian files: install.po, quick_start.po
  docs/source/locales/ru/LC_MESSAGES/install.po
  docs/source/locales/ru/LC_MESSAGES/quick_start.po
Labels: documentation
