Repository eternnoir/pyTelegramBotAPI, pull requests merged in 2022-12, with the labels that each got.

#1818 Translated to russian file: util.po
  docs/source/locales/ru/LC_MESSAGES/util.po
Labels: translation

#1832 Fix bug related to get_user_profile_photos
  telebot/asyncio_helper.py
Labels: bug

#1831 Update reloader.py
  telebot/ext/reloader.py
Labels: bug

#1844 Fix #1843
  telebot/formatting.py
Labels: bug, confirmed

#1845 Partly translated files: sync_version.po
  docs/source/locales/ru/LC_MESSAGES/sync_version.po
Labels: documentation, translation
