Repository eternnoir/pyTelegramBotAPI, pull requests merged in 2022-10, with the labels that each got.

#1693 Logging improvements(still not 100%), file restarts on file changes(needs tests), and more
  examples/asynchronous_telebot/detect_changes.py
  examples/detect_changes.py
  setup.py
  telebot/__init__.py
  telebot/async_telebot.py
  telebot/asyncio_helper.py
  telebot/ext/reloader.py
Labels: comming soon, under discussion, in the backlog, code, under testing

#1747 Update __init__.py
  telebot/__init__.py
Labels: bug, confirmed

#1748 Added warning for non_stop=False
  telebot/async_telebot.py
Labels: warning

#1742 Support ContinueHandling
  examples/asynchronous_telebot/continue_handling.py
  examples/continue_handling.py
  telebot/__init__.py
  telebot/async_telebot.py
  telebot/asyncio_handler_backends.py
  telebot/handler_backends.py
Labels: enhancement, comming soon, code, under testing, under review
